version: '3.7'

services:

  react:
    container_name: admin-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/admin-panel-react'
      - '/admin-panel-react/node_modules'
    ports:
      - "3010:3000"
    restart: always



